#title:Select all the movies from Brad Pitt and Angelina Jolie
#tags:1 graph pattern,1 variable,2 conditions
#color:ex-blue
#img:cartoon-female
    
SELECT ?movie WHERE {
  ?movie a tto:Movie
  { ?movie tto:performedby tto:BradPitt }
  UNION
  { ?movie tto:performedby tto:AngelinaJolie }
}