#title:Select all the available movies
#tags:1 graph pattern,1 variable
#color:ex-blue
#img:cartoon-rdf-type
    
SELECT DISTINCT *
	WHERE {
  ?s rdf:type tto:Movie
}

# Remember that in the turtle data (Data tab) we can see: 
#
# 'a' can also be used instead of 'rdf:type' 
# 'a' is a synonym of 'rdf:type'
